[package]
name = "sv_circuit"
version = "0.1.1"
authors = ["Eric Hennenfent <eric.hennenfent@trailofbits.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.0"
maplit = "1.0.2"
rand = "0.7.3"
counter = "0.5.2"
clap = "4.0.27"
itertools = "0.10.0"
mcircuit = { git = "https://github.com/trailofbits/mcircuit" }
num-traits = "0.2"
serde = "1.0.124"
bincode = "1.3.2"
indicatif = "0.16.1"
fnv = "1.0.7"
thiserror = "1.0.30"
anyhow = "1.0.51"

[lib]
name = "sv_circuit"
crate-type = ["lib", "cdylib"]

[[bin]]
name = "sv-compositor"
path = "src/main.rs"

[[bin]]
name = "lucid"
path = "src/lucid.rs"

[[bin]]
name = "sv-bin-stat"
path = "src/stat.rs"

